DATA TOOLKIT 

In [1]:
# Numpy >> numerical python 
# 2005 by travis oliphant
# before 2005 there were special matematical tools (similar to Tara,linga)

In [1]:
import numpy as np # as is alias 

In [5]:
import numpy as np

In [4]:
np.__version__

'2.1.0'

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

In [6]:
lis = [1,2,3,"pwskills",3+5j,True,1.2] # list stores heterogenous data
type(lis) 

list

In [7]:
# numpy stores the data in a numpy array
# an array is a , container/data structure used to store data of same data type >> homogenous


In [8]:
# why numpy ? already we ahve list, c  isone of the fastest prog lang after c++

# numpy is built using  C >> numpy computation is fast 
# due to array >> since it stores only homogenous data ,numpy array  is fastter
# since it stores homogenous data >> contigous/continuos memory location  
# mathemtical computtion is fast

In [9]:
l = [1,2,3,4,5] # numpy array is homogenous >> all elemnent can be integer, float , string, 
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [10]:
type(arr) # numpy.ndarray >> n dimensuonal array

numpy.ndarray

In [11]:
l = [1,2,3,4,5,"Swaraj"]
arr1 = np.array(l)
arr1

array(['1', '2', '3', '4', '5', 'Swaraj'], dtype='<U21')

In [12]:
type(arr1) # array stores homogenous data >> converted into string

numpy.ndarray

In [13]:
l = [1,2,3,4,5,1.4]
arr1 = np.array(l)
arr1 # every value will be converted into float 

array([1. , 2. , 3. , 4. , 5. , 1.4])

In [14]:
l = [1,2,3,4,5,1.4,"swaraj"]
arr = np.array(l)
arr

array(['1', '2', '3', '4', '5', '1.4', 'swaraj'], dtype='<U32')

In [15]:
type(arr)

numpy.ndarray

In [16]:
arr.ndim # aree has only rows

1

In [17]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1 # it became an two dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr1.ndim

2

In [19]:
mat = np.matrix([1,2,3,4]) # matrix is a specialized arrays of two deimnsional 

In [20]:
type(mat)

numpy.matrix

In [21]:
mat.ndim

2

In [22]:
# # to understand the dimension , see the no of opening /closing square braccet[]
# if [  ] = one dimension 
# if [[  ]] = two dimension
# if [[[  ]]] = three dimenion

In [23]:
np.matrix([[[1,2],[1,5],[3,6]]]) # it will throw >> ValueError: matrix must be 2-dimensional

ValueError: matrix must be 2-dimensional

In [24]:
arr =np.array([[[1,2],[1,5],[3,6]]]) 
arr

array([[[1, 2],
        [1, 5],
        [3, 6]]])

In [25]:
arr.ndim

3

In [26]:
#more ways to array
l = [1,2,3] 
np.asarray(l) # initial function asarray to convert to an array, np.arraay came after this

array([1, 2, 3])

In [28]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [29]:
# asanyarray will convert  the input to an ndarray , but pass ndarray as subclass through 
# if something is already an array or part of array it will simply allow to pass throug it

In [30]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [31]:
mat

matrix([[1, 2, 3, 4]])

In [32]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [34]:
t = ([1,2,3],[4,5,6])
type(t)

tuple

In [35]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [38]:
# accessing the elements of the array (by index)
print(arr[0])

1


In [39]:
# array is mutable  >>> you can chane the value
arr[0]=100

In [40]:
arr

array([100,   2,   3,   4,   5,   6])

In [41]:
# a and arr will point to same memory loctaion,so if there is any chnge in a / array it will reflect on both 
a = arr
a

array([100,   2,   3,   4,   5,   6])

In [42]:
arr

array([100,   2,   3,   4,   5,   6])

In [43]:
# shallow copy >>change in one array lead to change in another 
a[0] = 500
a

array([500,   2,   3,   4,   5,   6])

In [44]:
arr

array([500,   2,   3,   4,   5,   6])

In [45]:
# deep copy
arr = np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [46]:
b = arr.copy() # cahnnge in one array will not cahnge in another
b

array([1, 2, 3, 4, 5])

In [47]:
b[0] = 100
b

array([100,   2,   3,   4,   5])

In [48]:
arr

array([1, 2, 3, 4, 5])

In [49]:
# to creat an array >> np.array , np.asarray , np.asanarray

In [51]:
# multiple approach to generate an array

In [6]:
arr1 = np.fromfunction(lambda i,j: i==j,(3,3)) #Construct an array by executing a function over each coordinate.

In [7]:
arr1.ndim

2

In [8]:
arr1.shape #shape of array

(3, 3)

In [56]:
arr1.size # no of elements

9

In [58]:
# True is stored as 1 and false is stored as false 
True-False

1

In [9]:
arr2 = np.fromfunction(lambda i, j : i*j,(3,3))
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [64]:
arr2.ndim

2

In [61]:
arr2.size

9

In [63]:
arr2.shape

(3, 3)

In [65]:
for i in range(5):
    print(i)


0
1
2
3
4


In [66]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [70]:
(i for i in range(5))

<generator object <genexpr> at 0x0000015D5C990280>

In [78]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [10]:
iterator = (i for i in range(5))

In [11]:
iterator

<generator object <genexpr> at 0x000002C17A4A4700>

In [12]:
np.fromiter(iterator, int) # creat a new 1-D array from an iterable obect

array([0, 1, 2, 3, 4])

In [88]:
np.fromiter(iterator, float) # creat a new 1-D array from an iterable obect

array([0., 1., 2., 3., 4.])

In [13]:
np.fromstring("22 23 24", sep = " ") # bydefault its float

array([22., 23., 24.])

In [89]:
np.fromstring("22 23 24", sep = " ", dtype=int) # value inside a sting should be numerical

array([22, 23, 24])

In [91]:
# String character you have to use split
string = "swaraj,appu,aajay"
string.split(",")

['swaraj', 'appu', 'aajay']

In [92]:
np.array(string.split(","))

array(['swaraj', 'appu', 'aajay'], dtype='<U6')

In [93]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
# another methode of numpy >> to generate sequence of number
np.arange(1,10) # arange returns evenly specified values within a given interval, by default step is one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [97]:
np.linspace (1,5, 10) # give me 10 numbers between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [1]:
class Vehicle:
    def vehicle_type(self):
        print("This is a vehicle")
    def tyre(self,tyre=""):
        if tyre == 2:
            print("This is a two whiler vehicle")
        elif tyre==3:
            print("This is an auto")
        elif tyre==4:
            print("This is a car")
        else:
            print("This is a truck")

In [6]:
vehicle = Vehicle()
vehicle.vehicle_type()

this is a vehicle
