numpy advnce - 1

In [3]:
import numpy as np

In [5]:
a = np.zeros(5) # return a new array of given shape and type , filled with zeros

In [6]:
a

array([0., 0., 0., 0., 0.])

In [7]:
a.ndim

1

In [8]:
np.zeros(10, dtype =int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
b.ndim

2

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [18]:
(np.ones(5,dtype=str))

array(['1', '1', '1', '1', '1'], dtype='<U1')

In [22]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
np.twos(5) # not exist in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [26]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [28]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
arr.ndim

2

In [32]:
# 3 dimensional array
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
arr = np.zeros((3,3,4)) # 3-d ,3row , 4colum with one one outer dimension
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
arr.ndim

3

In [7]:
b = np.zeros((1,1,3,4))
b

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [6]:
b.ndim

4

In [10]:
c = np.zeros((1,1,1,3,4)) #5D array
c

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [11]:
c.ndim

5

In [18]:
arr = np.zeros((3,4),dtype=int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
a = arr+5
a

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [22]:
a * 4  # same concept a*4 = 20

array([[20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

In [24]:
a - 1

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [26]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
print(np.empty((3,3)))#returns a new array of given shape and type,  with out initializing entries >> entries inthe array can be anything random

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [43]:
#optinal >> random module
import random
random.choice((1,2,3,4,5))

4

In [44]:
random.choice("Swaraj")

'S'

In [45]:
random.randrange(1,10)

2

In [47]:
random.random() # a random number generated be 0(include) and 1(exclude)

0.11988352292422177

In [48]:
lis = [1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [50]:
random.shuffle(lis)

In [51]:
random.uniform(7,14) # uniform distribution

13.421884790809038

In [53]:
# random nubers related concept in numpy

np.array([])

array([], dtype=float64)

In [54]:
np.random.random_sample()

0.32212058139961

In [55]:
np.random.random_sample(5, ) # one dimension array of 5random nos

array([0.4102113 , 0.62491081, 0.45190344, 0.32706528, 0.74619931])

In [61]:
np.random.rand(1)

array([0.96108267])

In [62]:
np.random.rand(2,3)

array([[0.65988402, 0.2390452 , 0.86987212],
       [0.7324609 , 0.9004986 , 0.40525809]])

In [64]:
np.random.randn(2,3) #Return a sample (or samples) from the "standard normal" distribution.

array([[-1.72596929, -1.17632553,  0.97115428],
       [-0.68890653,  0.48530398,  0.64208738]])

In [65]:
np.random.randint(1,5)

4

In [71]:
arr = np.random.randint(1,5, size = (3,4)) # 5 start from 1 and end at 5-1 and give array of shape 3,4
arr

array([[2, 1, 3, 3],
       [1, 4, 1, 3],
       [1, 3, 2, 2]], dtype=int32)

In [70]:
arr.ndim

2

In [78]:
arr.size

12

In [72]:
arr.shape

(3, 4)

In [73]:
arr

array([[2, 1, 3, 3],
       [1, 4, 1, 3],
       [1, 3, 2, 2]], dtype=int32)

In [80]:
#reshape of array
arr1 = arr.reshape(2,6) # returns an array containing the same data with a new number
arr1

array([[2, 1, 3, 3, 1, 4],
       [1, 3, 1, 3, 2, 2]], dtype=int32)

In [81]:
arr1.size

12

In [82]:
arr1.shape

(2, 6)

In [83]:
arr1.ndim

2

In [86]:
# arrasy size will never change , always reshape parameter should be multiplication of original array size

In [88]:
arr

array([[2, 1, 3, 3],
       [1, 4, 1, 3],
       [1, 3, 2, 2]], dtype=int32)

In [89]:
arr.reshape(3,2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [90]:
arr.reshape(3,2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [91]:
arr.reshape(4,3)

array([[2, 1, 3],
       [3, 1, 4],
       [1, 3, 1],
       [3, 2, 2]], dtype=int32)

In [92]:
arr.reshape(12,1)

array([[2],
       [1],
       [3],
       [3],
       [1],
       [4],
       [1],
       [3],
       [1],
       [3],
       [2],
       [2]], dtype=int32)

In [95]:
# case when you dont know in shape what should be the row or colum count
# use -1 (any negative value for rows or column
arr.reshape(4,-1)

array([[2, 1, 3],
       [3, 1, 4],
       [1, 3, 1],
       [3, 2, 2]], dtype=int32)

In [96]:
arr.reshape(4,-600)

array([[2, 1, 3],
       [3, 1, 4],
       [1, 3, 1],
       [3, 2, 2]], dtype=int32)

In [97]:
arr.reshape(-1,4)

array([[2, 1, 3, 3],
       [1, 4, 1, 3],
       [1, 3, 2, 2]], dtype=int32)

In [101]:
arr.reshape(12,1).base # to see the original arry

array([[2, 1, 3, 3],
       [1, 4, 1, 3],
       [1, 3, 2, 2]], dtype=int32)

In [103]:
arr.reshape(2,2,3) # multiplication should be equals to array size

array([[[2, 1, 3],
        [3, 1, 4]],

       [[1, 3, 1],
        [3, 2, 2]]], dtype=int32)

In [104]:
arr.reshape(1,2,2,3)

array([[[[2, 1, 3],
         [3, 1, 4]],

        [[1, 3, 1],
         [3, 2, 2]]]], dtype=int32)

In [105]:
arr.reshape(1,2,2,3).ndim

4

In [107]:
arr.reshape(4,3,1) # 3rows,1column , 4 dimension

array([[[2],
        [1],
        [3]],

       [[3],
        [1],
        [4]],

       [[1],
        [3],
        [1]],

       [[3],
        [2],
        [2]]], dtype=int32)

In [110]:
# condition on array
arr1 = np.random.randint(1,10,(5,6))
arr1

array([[8, 6, 8, 8, 2, 8],
       [4, 5, 6, 6, 6, 2],
       [9, 7, 5, 2, 7, 9],
       [1, 9, 2, 1, 3, 9],
       [9, 2, 7, 8, 6, 8]], dtype=int32)

In [112]:
arr1.shape

(5, 6)

In [113]:
arr1.size

30

In [114]:
arr1.ndim

2

In [115]:
arr1

array([[8, 6, 8, 8, 2, 8],
       [4, 5, 6, 6, 6, 2],
       [9, 7, 5, 2, 7, 9],
       [1, 9, 2, 1, 3, 9],
       [9, 2, 7, 8, 6, 8]], dtype=int32)

In [116]:
arr1 > 3

array([[ True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True, False],
       [ True,  True,  True, False,  True,  True],
       [False,  True, False, False, False,  True],
       [ True, False,  True,  True,  True,  True]])

In [118]:
arr1[arr1 > 3] # select all the elements of arr1  where the condition is true

array([8, 6, 8, 8, 8, 4, 5, 6, 6, 6, 9, 7, 5, 7, 9, 9, 9, 9, 7, 8, 6, 8],
      dtype=int32)

In [120]:
arr1[arr1 < 3]

array([2, 2, 2, 1, 2, 1, 2], dtype=int32)

In [121]:
arr1

array([[8, 6, 8, 8, 2, 8],
       [4, 5, 6, 6, 6, 2],
       [9, 7, 5, 2, 7, 9],
       [1, 9, 2, 1, 3, 9],
       [9, 2, 7, 8, 6, 8]], dtype=int32)

In [122]:
# to access elements in array

arr1[0]

array([8, 6, 8, 8, 2, 8], dtype=int32)

In [123]:
arr1[1]

array([4, 5, 6, 6, 6, 2], dtype=int32)

In [124]:
arr1[2]

array([9, 7, 5, 2, 7, 9], dtype=int32)

In [125]:
arr1[2][2]

np.int32(5)

In [126]:
arr1

array([[8, 6, 8, 8, 2, 8],
       [4, 5, 6, 6, 6, 2],
       [9, 7, 5, 2, 7, 9],
       [1, 9, 2, 1, 3, 9],
       [9, 2, 7, 8, 6, 8]], dtype=int32)

In [128]:
arr1[3][1]

np.int32(9)

In [129]:
arr1

array([[8, 6, 8, 8, 2, 8],
       [4, 5, 6, 6, 6, 2],
       [9, 7, 5, 2, 7, 9],
       [1, 9, 2, 1, 3, 9],
       [9, 2, 7, 8, 6, 8]], dtype=int32)

In [135]:
# from 0th row to 2nd row
arr1[0:3]

array([[8, 6, 8, 8, 2, 8],
       [4, 5, 6, 6, 6, 2],
       [9, 7, 5, 2, 7, 9]], dtype=int32)

In [136]:
# 0 to 2nd row and 2nd cl
arr1[0:3,[0,2]]

array([[8, 8],
       [4, 6],
       [9, 5]], dtype=int32)

array([[8, 8],
       [4, 6],
       [9, 5]], dtype=int32)

In [137]:
arr1

array([[8, 6, 8, 8, 2, 8],
       [4, 5, 6, 6, 6, 2],
       [9, 7, 5, 2, 7, 9],
       [1, 9, 2, 1, 3, 9],
       [9, 2, 7, 8, 6, 8]], dtype=int32)

In [143]:
#slicing on both row and column togeather
arr1

array([[8, 6, 8, 8, 2, 8],
       [4, 5, 6, 6, 6, 2],
       [9, 7, 5, 2, 7, 9],
       [1, 9, 2, 1, 3, 9],
       [9, 2, 7, 8, 6, 8]], dtype=int32)

In [147]:
arr1[0:3,1:3]

array([[6, 8],
       [5, 6],
       [7, 5]], dtype=int32)

In [148]:
#  0th and1st 
arr1[0:3,[0,1]]

array([[8, 6],
       [4, 5],
       [9, 7]], dtype=int32)

In [149]:
arr1[0]

array([8, 6, 8, 8, 2, 8], dtype=int32)

In [150]:
arr1[0,[1,3]]

array([6, 8], dtype=int32)

In [151]:
arr1

array([[8, 6, 8, 8, 2, 8],
       [4, 5, 6, 6, 6, 2],
       [9, 7, 5, 2, 7, 9],
       [1, 9, 2, 1, 3, 9],
       [9, 2, 7, 8, 6, 8]], dtype=int32)

In [152]:
arr1[2:4,[0,3]]

array([[9, 2],
       [1, 1]], dtype=int32)

In [153]:
arr1[2:5]

array([[9, 7, 5, 2, 7, 9],
       [1, 9, 2, 1, 3, 9],
       [9, 2, 7, 8, 6, 8]], dtype=int32)

In [155]:
arr1[2:4, 0:2]

array([[9, 7],
       [1, 9]], dtype=int32)

In [163]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [164]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [165]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [2, 1, 2]], dtype=int32)

In [168]:
arr1+arr2 # index wise element addition

array([[4, 3, 3],
       [4, 3, 2],
       [4, 3, 3]], dtype=int32)

In [169]:
arr1-arr2 # index wise element substraction

array([[ 0, -1,  1],
       [ 0,  1,  0],
       [ 0,  1, -1]], dtype=int32)

In [170]:
arr1*arr2 # index wise element mutiplication

array([[4, 2, 2],
       [4, 2, 1],
       [4, 2, 2]], dtype=int32)

In [171]:
arr1/arr2 # # index wise element division

array([[1. , 0.5, 2. ],
       [1. , 2. , 1. ],
       [1. , 2. , 0.5]])

In [175]:
4/0

ZeroDivisionError: division by zero

In [174]:
arr1/0

C:\Users\user\AppData\Local\Temp\ipykernel_6320\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [176]:
arr2/0

C:\Users\user\AppData\Local\Temp\ipykernel_6320\4133987296.py:1: RuntimeWarning: divide by zero encountered in divide
  arr2/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [177]:
# matrix multiplication >> matrix is secialised by 2-d array
# matrix multiplication is diffrent from index wise multiplication

In [178]:
arr1@arr2

array([[10,  7,  7],
       [10,  7,  6],
       [10,  7,  6]], dtype=int32)

In [179]:
np.dot(arr1,arr2) # another way of matrix multiplication 

array([[10,  7,  7],
       [10,  7,  6],
       [10,  7,  6]], dtype=int32)

In [182]:
# broadcasting

arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [183]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [184]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [185]:
a = np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [186]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [189]:
# transpose >> converting rows to column and column to rows (works only 2D data)

array([1, 2, 3, 4])

In [191]:
a = np.array([[1,2,3,4]])
a.T

array([[1],
       [2],
       [3],
       [4]])

In [192]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [193]:
arr1.T

array([[2, 2, 2],
       [1, 2, 2],
       [2, 1, 1]], dtype=int32)