In [1]:
import numpy as np

In [4]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [5]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [1, 1, 1]], dtype=int32)

In [6]:
arr1

array([[2, 2, 2],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [8]:
arr1.flatten() # return a copy of the array collapsed into dimension 

array([2, 2, 2, 2, 1, 2, 1, 2, 1], dtype=int32)

In [9]:
arr2.flatten() # return a copy of the array collapsed into dimension 

array([1, 1, 1, 1, 2, 2, 1, 1, 1], dtype=int32)

In [16]:
# expand dimension 
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [13]:
arr.ndim

1

In [19]:
np.expand_dims(arr,axis=0) #Expand the shape of an array. >> increase the dimension by 1 in the provided axis , 0 , means rows(x-axis and 1 mon colums y-axis) 

array([[1, 2, 3, 4]])

In [20]:
np.expand_dims(arr,axis=1) # column wise

array([[1],
       [2],
       [3],
       [4]])

In [21]:
np.expand_dims(arr,axis=1).ndim

2

In [27]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.expand_dims(arr,axis=0) 

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
np.expand_dims(arr,axis=0).ndim

3

In [29]:
np.expand_dims(arr,axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [30]:
np.expand_dims(arr,axis=1).ndim

3

In [35]:
a = np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [38]:
a.ndim

2

In [40]:
#squizing the dimension  by 1 dimension
np.squeeze(a) #Remove axes of length one from 'a'

array([1, 2, 3])

In [41]:
a.ndim

2

In [42]:
a 

array([[1],
       [2],
       [3]])

In [43]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [44]:
arr1

array([[2, 2, 2],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [45]:
np.repeat(arr1,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1], dtype=int32)

In [46]:
np.repeat(arr1,2,axis=0)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 1, 2],
       [2, 1, 2],
       [1, 2, 1],
       [1, 2, 1]], dtype=int32)

In [47]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [1, 1, 1]], dtype=int32)

In [53]:
np.repeat(arr2, 2, axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 2, 2],
       [1, 2, 2],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [54]:
np.repeat(arr2,3,axis=1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [55]:
a

array([[1],
       [2],
       [3]])

In [56]:
np.roll(a,-1) #shifts place 

array([[2],
       [3],
       [1]])

In [57]:
np.roll(a,-2)

array([[3],
       [1],
       [2]])

In [58]:
c = np.array([[1,2],[3,4],[5,6],[7,8]])

In [59]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [60]:
np.roll(c,-1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [62]:
np.roll(c,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [63]:
np.roll(c,2,axis = 0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [64]:
arr1

array([[2, 2, 2],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [65]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [1, 1, 1]], dtype=int32)

In [66]:
arr1+arr2

array([[3, 3, 3],
       [3, 3, 4],
       [2, 3, 2]], dtype=int32)

In [67]:
arr1-arr2

array([[ 1,  1,  1],
       [ 1, -1,  0],
       [ 0,  1,  0]], dtype=int32)

In [68]:
arr2-arr1

array([[-1, -1, -1],
       [-1,  1,  0],
       [ 0, -1,  0]], dtype=int32)

In [69]:
arr2+arr1

array([[3, 3, 3],
       [3, 3, 4],
       [2, 3, 2]], dtype=int32)

In [70]:
arr1*arr2

array([[2, 2, 2],
       [2, 2, 4],
       [1, 2, 1]], dtype=int32)

In [71]:
arr1 > arr2

array([[ True,  True,  True],
       [ True, False, False],
       [False,  True, False]])

In [72]:
arr1

array([[2, 2, 2],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [73]:
~arr1

array([[-3, -3, -3],
       [-3, -2, -3],
       [-2, -3, -2]], dtype=int32)

In [76]:
#operations on numpy string array
d = np.array(["pw","skills"])
d

array(['pw', 'skills'], dtype='<U6')

In [77]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [78]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [79]:
# mathematical functions
arr1

array([[2, 2, 2],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [81]:
np.sin(arr1)

array([[0.90929743, 0.90929743, 0.90929743],
       [0.90929743, 0.84147098, 0.90929743],
       [0.84147098, 0.90929743, 0.84147098]])

In [82]:
np.cos(arr1)

array([[-0.41614684, -0.41614684, -0.41614684],
       [-0.41614684,  0.54030231, -0.41614684],
       [ 0.54030231, -0.41614684,  0.54030231]])

In [83]:
np.tan(arr1)

array([[-2.18503986, -2.18503986, -2.18503986],
       [-2.18503986,  1.55740772, -2.18503986],
       [ 1.55740772, -2.18503986,  1.55740772]])

In [85]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.30103],
       [0.30103, 0.     , 0.30103],
       [0.     , 0.30103, 0.     ]])

In [86]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183]])

In [88]:
np.power(arr1,3)

array([[8, 8, 8],
       [8, 1, 8],
       [1, 8, 1]], dtype=int32)

In [89]:
np.max(arr1)

np.int32(2)

In [90]:
np.mean(arr1)

np.float64(1.6666666666666667)

In [91]:
np.min(arr1)

np.int32(1)

In [92]:
np.std(arr1)

np.float64(0.4714045207910317)

In [93]:
np.var(arr1)

np.float64(0.2222222222222222)

In [94]:
arr1-arr2

array([[ 1,  1,  1],
       [ 1, -1,  0],
       [ 0,  1,  0]], dtype=int32)

In [95]:
np.subtract(arr1,arr2)

array([[ 1,  1,  1],
       [ 1, -1,  0],
       [ 0,  1,  0]], dtype=int32)

In [96]:
np.multiply(arr1,arr2)

array([[2, 2, 2],
       [2, 2, 4],
       [1, 2, 1]], dtype=int32)

In [97]:
np.mod(arr1,arr2)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int32)

In [98]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        ]])

In [99]:
#sorting and searching in numpy array
e = np.array([4,5,3,1,2])

In [101]:
np.sort(e) # Return a sorted copy of an array.

array([1, 2, 3, 4, 5])

In [103]:
f = np.array([1,54,32,6,78,9,44])
f

array([ 1, 54, 32,  6, 78,  9, 44])

In [104]:
np.sort(f)

array([ 1,  6,  9, 32, 44, 54, 78])

In [105]:
np.searchsorted(f,170) #Find indices where elements should be inserted to maintain order.

np.int64(7)

In [107]:
f = np.array([1,54,32,6,78,0,9,44,0,0])
f

array([ 1, 54, 32,  6, 78,  0,  9, 44,  0,  0])

In [109]:
np.count_nonzero(f) #Counts the number of non-zero values in the array a

7

In [110]:
f[f>0]

array([ 1, 54, 32,  6, 78,  9, 44])

In [112]:
np.where(f>0) #same as above condition

(array([0, 1, 2, 3, 4, 6, 7]),)

In [114]:
np.extract(f>0,f) #same as above condition

array([ 1, 54, 32,  6, 78,  9, 44])

In [115]:
f

array([ 1, 54, 32,  6, 78,  0,  9, 44,  0,  0])

In [117]:
f.byteswap() # swap the bytes of the array elements

array([  72057594037927936, 3891110078048108544, 2305843009213693952,
        432345564227567616, 5620492334958379008,                   0,
        648518346341351424, 3170534137668829184,                   0,
                         0])

In [120]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [121]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [122]:
# numpy lnear algebra function (optional)
arr1

array([[2, 2, 2],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [123]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [1, 1, 1]], dtype=int32)

In [124]:
arr1@arr2

array([[6, 8, 8],
       [5, 6, 6],
       [4, 6, 6]], dtype=int32)

In [125]:
np.linalg.det(arr1)

np.float64(0.0)

In [127]:
np.linalg.det(arr2)

np.float64(0.0)

In [137]:
# np.linalg.inv(arr2) # shows erroe if determinat 0 

In [138]:
a = np.array([[7,5.3,-3],[3,-5,2],[3,5,-3]]) 
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 3. ,  5. , -3. ]])

In [140]:
b = np.array([16,24,3])

In [141]:
np.linalg.solve(a,b)

array([ 3.60816327, -4.7755102 , -5.35102041])