In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.0'

In [ ]:
# rray stores homogenous data

In [5]:
b= np.array([[1,2,3],[1,2,3]])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [7]:
b.ndim

2

In [8]:
# matrix .> specialized 2d array
np.matrix([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [ ]:
np.matrix([1,2,3,4,5])

In [9]:
l = [1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [10]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [11]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [12]:
t = (1,2,3,4,True)
np.array(t)

array([1, 2, 3, 4, 1])

In [13]:
d ={"ram":500,"shaym":300}
np.array(d)

array({'ram': 500, 'shaym': 300}, dtype=object)

In [1]:
True | False 

True

In [3]:
import pandas as pd